# ====================================================
# ====================================================
# ====================================================
# =====================log configuration==============
[log_formatter]
fmt = "[%(asctime)s %(levelname)s %(name)s] %(message)s"
datefmt = "%Y:%m:%d %H:%S:%M"

[log_notice_formatter]
fmt = "[%(asctime)s %(levelname)s] %(name)s 记录了一条异常日志！"
datefmt = "%Y:%m:%d %H:%S:%M"

# =====================system log configuration ======
[log_system]
name = "System_Logger_<name>"

level = "DEBUG"
dirname = "./logs/systems/<name>"
handlers = ["log_debug_rotatingFileHandler","log_warning_rotatingFileHandler","log_error_streamHandler","log_error_rotatingFileHandler"]

# system handler

[log_debug_rotatingFileHandler]
filename = "<name>_system_debug.log"
mode = "a"
maxBytes = 5242880 # 5 MB
backupCount = 20

handlerType = "RotatingFileHandler"
level = "DEBUG"
formatter = "log_formatter"


[log_warning_rotatingFileHandler]
filename = "<name>_system_warning.log"
mode = "a"
maxBytes = 5242880 # 5 MB
backupCount = 20

handlerType = "RotatingFileHandler"
level = "WARNING"
level_filters = ["WARNING"]
formatter = "log_formatter"

[log_error_rotatingFileHandler]
filename = "<name>_system_error.log"
mode = "a"
maxBytes = 5242880 # 5 MB
backupCount = 20

handlerType = "RotatingFileHandler"
level = "ERROR"
formatter = "log_formatter"

[log_error_streamHandler]

handlerType = "StreamHandler"
level = "ERROR"
formatter = "log_formatter"

# =====================user log configuration ======
[log_user]
name = "<name>_user_log"

dirname = "./logs/users/<name>"
level = "INFO"
handlers = ["log_userinfo_rotatingFile_hander","log_user_streamHandler","log_userWarning_rotatingFileHandler"]

# user log handler
[log_userinfo_rotatingFile_hander]
filename = "<name>_user_info.log"
mode = "a"
maxBytes = 5242880 # 5 MB
backupCount = 20

handlerType = "RotatingFileHandler"
level = "INFO"
formatter = "log_formatter"

[log_user_streamHandler]

handlerType = "StreamHandler"
level = "WARNING"
formatter = "log_notice_formatter"

[log_userWarning_rotatingFileHandler]
filename = "<name>_user_warning.log"
mode = "a"
maxBytes = 5242880 # 5 MB
backupCount = 20

handlerType = "RotatingFileHandler"
level = "WARNING"
formatter = "log_formatter"

