[sqlite]

[sqlite.engine]
        url = "sqlite:///test_sqlite.db"
        echo = false

[sqlite.user]
        successed_login_times=0
        failed_login_times=0

        user_permission=["default"]
        auth_group="default"

[sqlite.group]
        max_successed_login_times= 300
        max_failed_login_times= 5
        expired_time= "2030-01-01 00:00:00"
        is_deleted=false
        group_comment="default"

        group_permission=["default"]

[sqlite.permission]
        permission_name="default"
        permission_docu="默认权限"

[sqlite.datetemplate]
        date_string = "2030-01-01 00:00:00"
        format = "%Y-%m-%d %H:%M:%S"

